### ISSUE TITLE
Sync Step 1 error - Could not update note

### ISSUE THREAD

**Issue by brightghost** [cpbotha/nvpy#174]
I have nvpy .9.7 installed on Debian Stretch from `apt`. Was working fine as recently as 2018-12, but today I opened and am greeted with this error:

`Sync Step 1 error - Could not update note [uuid] to server: HTTP Error 404: Not Found`

Status bar reports 'Could not connect to SimpleNote server'. Nothing informative in the log, just a bunch of:

```
2019-02-17 17:43:20,827 - DEBUG - nvpy logging initialized
2019-02-17 17:43:20,827 - DEBUG - config read from ['/home/swlkr/.nvpy.cfg']
2019-02-17 17:43:21,150 - DEBUG - Starting full sync.
2019-02-17 17:43:29,004 - DEBUG - Updating note d4bd4d28fcff11e8937bd10e223f4b48 (local key c4d6ff28aa2c62b245c27f0d9a5102) to server.
2019-02-17 17:43:33,025 - DEBUG - Updating note d4bd4d28fcff11e8937bd10e223f4b48 (local key c4d6ff28aa2c62b245c27f0d9a5102) to server.
[etc.]

```

 Maybe just be an outage on SimpleNote's end? Tried removing my local database but still no luck. I don't see anything in the release notes regarding a breaking change in the API, though I do see a concerning notice about [an API deprecation in 2018-10](https://simplenote.com/developers/) on SimpleNote's site. Anyway, I tried downloading the latest dev version to test but am unable to run it (see [#168](https://github.com/cpbotha/nvpy/issues/168#issuecomment-464531472)).

**Comment by yuuki0xff** [comment]
Please try the latest development version. You can install it by run the following command.
```bash
$ pip install 'git+https://github.com/cpbotha/nvpy.git#egg=nvpy'
```

I using it everyday, but it seems to be working without any problems.

**Comment by yuuki0xff** [comment]
Additional explanation:
nvpy v1.0.0 or earlier are no longer function because the Legacy Simplenote API was obsoleted.  The latest development version supports new API (See #159).  So the simplenote synchronization feature will work completly.

A long time has passed from latest release.  I will release a new version some time soon.

**Comment by Vetgans** [comment]
I've got the exact same problem: _Sync Step 1 error - Could not update note_
Tried the aforementioned solution of
_pip install 'git+https://github.com/cpbotha/nvpy.git#egg=nvpy'_
to install the latest development version, but apparently it installs version 1.0.0.:

> Successfully installed Markdown-3.0.1 docutils-0.14 nvpy-1.0.0 simplenote-2.1.0


Consequently still _Sync Step 1 error - Could not update note_

OS: Kubuntu 16.04.

**Comment by yuuki0xff** [comment]
Could you re-run the `pip install` command with `--upgrade` option?
```bash
$ pip install --upgrade 'git+https://github.com/cpbotha/nvpy.git#egg=nvpy'
```

If the problem remains, please look for error messages in log file and paste it.  The log file will be located at `~/.nvpy/nvpy.log` .  It will help us to fix the problem.

**Comment by Vetgans** [comment]
After messing around with upgrading pip, downgrading pip, trying to install and/or run things differently with python 2 and 3 and so on, everything is working again eventually.
It would probably be helpful for others if i could reproduce the exact steps, but unfortunately i can't. In the end it came down to https://github.com/cpbotha/nvpy/issues/168#issuecomment-441864442. That was one of the first things i tried, but to no success initially. Now it's working fine though, but i can't pinpoint why it is now and wasn't before. I'm sorry i can't be more helpful.

So thanks for the update and the help. The development(?) version that is working now, still shows version number 1.0.0.. Is that correct?

**Comment by yuuki0xff** [comment]
I released v1.1.0 which fixed this problem.

> Development version still having number 1.0.0. is very confusing, particularly because of comment #174 (comment):

I apologize for the confusion.  From now on, adding "-dev" suffix to version number for identify the release version or development version.

**Comment by laertis** [comment]
In case someone bumps onto this again. None of the above worked for me except the following.

I didn't remember BUT I have installed nvPy on Ubuntu through the software center.
Although upgrading from pip changed the version of nvPy in "about" section the problem persisted

What I had to do is.
- Uninstall nvPy from software center
- mv ~/.nvpy ~/.nvpy.bak
- pip install 'git+https://github.com/cpbotha/nvpy.git#egg=nvpy'

As the last command above managed to install Markdown 3.1 for me which I couldn't upgrade with pip earlier

**Comment by frbayart** [comment]
> In case someone bumps onto this again. None of the above worked for me except the following.
> 
> I didn't remember BUT I have installed nvPy on Ubuntu through the software center.
> Although upgrading from pip changed the version of nvPy in "about" section the problem persisted
> 
> What I had to do is.
> 
> * Uninstall nvPy from software center
> * mv ~/.nvpy ~/.nvpy.bak
> * pip install 'git+https://github.com/cpbotha/nvpy.git#egg=nvpy'
> 
> As the last command above managed to install Markdown 3.1 for me which I couldn't upgrade with pip earlier

I just did it with `pip3` on Ubuntu eoan and `nvpy` works now.
